version: '3.9'
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=abc123.
      - POSTGRES_DB=flashcards
      - PGDATA=/var/lib/postgresql/data
    networks:
      - flashcards-net
    ports:
      - 5442:5432
    volumes:
      - postgres-flashcards:/var/lib/postgresql/data
networks:
  flashcards-net:
    name: flashcards-net
    external: false
volumes:
  postgres-flashcards:
    external: false
